### ISSUE TITLE
Concerns with filesystem/block device in the same SD card

### ISSUE THREAD

**Issue by ccli8** [ARMmbed/simple-mbed-cloud-client#13]
I am evaluating mbed cloud client 1.3.3 on **NUMAKER_PFM_NUC472**/**NUMAKER_PFM_M487** and send the same issue as https://github.com/ARMmbed/mbed-cloud-client-example/issues/10. In this case, my SD card is not partitioned (no MBR) but it is used for both FAT file system (to save KCM data) and block device (to save F/W update candidates). My concerns are:
1. There's potential risk that FAT file system and block device would overlap. Do you have plan to fix it?
1. FAT file system and block device both would call the underlying block device `init`/`deinit`? How do you coordinate them? Because `deinit` called by one end will make the other end to fail to work with the underlying block device.

**Comment by LiyouZhou** [comment]
I have not personally experienced it but we have had reports of weird behaviour of fat file system infringing on the update storage.

You can use https://github.com/ARMmbed/mbed-os/blob/master/features/filesystem/bd/SlicingBlockDevice.h to create two virtual blockdevices, one for fs one for update storage, so that there is absolutely no chance of them overwriting each other. And init and deinit wouldn't be an issue anymore because it is a virtual device.

Note if you are using virtual blockdevices, you need to be careful regards to the offset of update storage you set. https://github.com/ARMmbed/mbed-cloud-client-example/blob/master/mbed_app.json#L16

**Comment by ccli8** [comment]
> init and deinit wouldn't be an issue anymore because it is a virtual device.

Checking `SlicingBlockDevice` `init`/`deinit`, their `init`/`deinit` would call `_bd` `init`/`deinit`, where `_bd` is the underlying block device, e.g. `SDBlockDevice`. So `init`/`deinit` conflict between fs `SlicingBlockDevice` and update `SlicingBlockDevice` still exists.

```
int SlicingBlockDevice::init()
{
    int err = _bd->init();
```

```
int SlicingBlockDevice::deinit()
{
    return _bd->deinit();
```

@LiyouZhou

**Comment by LiyouZhou** [comment]
@ccli8 good point. There are 2 mitigations:
1. I think we don't call deinit from within the mbed-cloud-client library.
2. Init should be able to be called multiple times without side effects and the API is stateless. Of course there is no garantee but so far we have not seen problems.

There as been issues with the FlashIAP before https://github.com/ARMmbed/mbed-os/issues/4967. So we will have to fix it in the driver in mbed-os if problem arises again.

**Comment by ccli8** [comment]
@LiyouZhou How about define a rule for block device, for example:
1. `init` should be able to be called multiple times without side effect.
1. Utility block device (`ChainingBlockDevice`/`SlicingBlockDevice`/`MBRBlockDevice`) cannot call `deinit` of the underlying block device in their `deinit` to keep sharable not broken.

Then do you have a plan to apply the e.g. `SlicingBlockDevice` idea to fix the overlap issue?

**Comment by LiyouZhou** [comment]
>     init should be able to be called multiple times without side effect.
>     Utility block device (ChainingBlockDevice/SlicingBlockDevice/MBRBlockDevice) cannot call deinit of the underlying block device in their deinit to keep sharable not broken.
These two will probably be down to mbed-so API.

> Then do you have a plan to apply the e.g. SlicingBlockDevice idea to fix the overlap issue?
I will create an issue internally.

**Comment by ccli8** [comment]
I raise https://github.com/ARMmbed/mbed-os/issues/7455 to mbed-os to address the issue.

**Comment by MarceloSalazar** [comment]
@ccli8 thanks for raising #7455.
There is a PR merged to fix this: https://github.com/ARMmbed/mbed-os/issues/7455

**Comment by ccli8** [comment]
@MarceloSalazar So in next release of [Simple Cloud Client template application](https://github.com/ARMmbed/simple-mbed-cloud-client-template-restricted), you will also fix the overlap issue?

**Comment by MarceloSalazar** [comment]
Hi @ccli8 , I understand the overlap issue will need to be fixed in Mbed OS. If there isn't a ticket, please raise one!
The SMCC template application will be updated to newer versions of Mbed OS (with corresponding fixes), but you can also update the mbed-os.lib of your application earlier if needed.
